Update pipenv to remove broken option.
In pipenv 4.0.0, `--no-dashes` is removed and causes the command to fail:

```
➜  buttondown git:(master) ✗ pipenv lock --requirements --no-hashes
Error: no such option: --no-hashes
```

As far as I can tell, this breaks all heroku deployments that use pipenv since there's no way to specify a version of pipenv.  Removing the flag will presumably fix this.