Update pip to 22.0.4, setuptools to 60.10.0 and wheel to 0.37.1 (#1310)
- Update pip from 21.3.1 to 22.0.4 for Python 3.7+
- Update setuptools from 57.5.0 to:
  - 59.6.0 for Python 3.6
  - 60.10.0 for Python 3.7+
- Update wheel from 0.37.0 to 0.37.1 for Python 2.7 and Python 3.5+

The setuptools upgrade should resolve issues Pipenv users are seeing
with conflicting setuptools versions causing errors like:

```
Traceback (most recent call last):
  ...
  File "/app/.heroku/python/lib/python3.10/site-packages/pipenv/environment.py", line 553, in get_distributions
    pkg_resources = self.safe_import("pkg_resources")
  File "/app/.heroku/python/lib/python3.10/site-packages/pipenv/environment.py", line 92, in safe_import
    six.moves.reload_module(module)
  File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/.heroku/python/lib/python3.10/site-packages/pkg_resources/__init__.py", line 74, in <module>
    from pkg_resources.extern.jaraco.text import (
ModuleNotFoundError: No module named 'pkg_resources.extern.jaraco'
```

However, the setuptools upgrade also drops support for the deprecated `2to3`
feature, which may be used be a small number of legacy dependencies.

For example:

```
Collecting Flask-OpenID==1.2.5
  Downloading Flask-OpenID-1.2.5.tar.gz (43 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in Flask-OpenID setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

Affected apps should either:
- Update to a newer version of affected dependencies.
- Use a wheel rather than an sdist of those dependencies (wheels don't
  require the use of setuptools once created). For example by ensuring
  the Python version in use matches that of any published wheels (see the
  package's "Download files" section on pypi.org for which wheels exist), or
  by asking the package maintainer to upload wheels for an existing release.
- Pin to the previous buildpack release (v209), using:
  https://devcenter.heroku.com/articles/buildpacks#buildpack-references

Note: Pinning buildpack version should be used as a short-term workaround
only, and after any affected dependencies are fixed, apps should switch back
to the default stable-release buildpack alias of `heroku/python`.

Release notes:
https://pip.pypa.io/en/stable/news/#v22-0-4
https://setuptools.pypa.io/en/latest/history.html#v60-10-0
https://github.com/pypa/wheel/blob/0.37.1/docs/news.rst

Commits:
https://github.com/pypa/pip/compare/21.3.1...22.0.4
https://github.com/pypa/setuptools/compare/v57.5.0...v60.10.0
https://github.com/pypa/wheel/compare/0.37.0...0.37.1

Note: The new version of pip includes new progress bars, which have had
to be disabled using `--progress off` in order to reduce build log noise.

GUS-W-10538676.